scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
        - prometheus:9090
        - node-exporter:9100
        - pushgateway:9091
        - cadvisor:8080

  - job_name: docker
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.55:9323']
      
  - job_name: myapp
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.1.55:4200"]
      
remote_write:
  - url: "192.168.1.55:9090"
    basic_auth:
      username: "admin"
      password: "eyJrIjoiMlNEVWl5WGtZNDI5RThMWWJRT1NnZllHb21iajJFUTMiLCJuIjoidG9rZW4iLCJpZCI6MX0="

